"""Add Car and Model tables

Revision ID: 06250de69820
Revises: 36348c23537a
Create Date: 2025-04-30 23:46:24.098504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06250de69820'
down_revision = '36348c23537a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('carid', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('carid')
    )
    op.create_table('models',
    sa.Column('carid', sa.Integer(), nullable=False),
    sa.Column('modelid', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('construction_year', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['carid'], ['cars.carid'], ),
    sa.PrimaryKeyConstraint('carid', 'modelid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    op.drop_table('cars')
    # ### end Alembic commands ###
