"""Add Manager table

Revision ID: 36348c23537a
Revises: 6c8ce31998ab
Create Date: 2025-04-30 21:49:33.575023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36348c23537a'
down_revision = '6c8ce31998ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('ssn', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ssn'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('People')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='People_pkey')
    )
    op.drop_table('managers')
    # ### end Alembic commands ###
